try{
    var a = 1;
    throw "ye";
}catch(e){
    println(e); // should succeed
    println(a); // should get error here
    println("Should have gotten an error by now :(");
}